### ISSUE TITLE
URL not working anymore

### ISSUE THREAD

**Issue by M51a** [andrescavallin/lichess-dgt-boards-browser#1]
The URL [https://andrescavallin.github.io/lichess-dgt-boards-browser/](https://andrescavallin.github.io/lichess-dgt-boards-browser/) is not working anymore (404).

**Comment by andrescavallin** [comment]
Hello @M51a it has been integrated into Lichess code . Please visit the beta at:
https://lichess.org/dgt

**Comment by M51a** [comment]
I just figured that out right after raising this issue.. Great work! Worked flawlessly.. 👍
